# Generated by Django 3.2.25 on 2024-10-28 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='deleted date')),
                ('album_title', models.CharField(max_length=255, verbose_name='アルバムタイトル')),
                ('release_year', models.CharField(max_length=4, verbose_name='制作年')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apiv1.artist')),
            ],
            options={
                'db_table': 'albums',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='deleted date')),
                ('title', models.CharField(max_length=20, verbose_name='タイトル')),
                ('release_year', models.CharField(max_length=4, verbose_name='制作年')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apiv1.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv1.artist')),
            ],
            options={
                'verbose_name': '歌',
                'verbose_name_plural': '歌',
                'db_table': 'songs',
            },
        ),
    ]
